name: "React Native Android Build"
on:
  push:
    branches:
      - master
jobs:
  install-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install npm dependencies
        run: |
          npm install
          
  build-android-and-test:
    needs: install-npm
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install npm dependencies
        run: |
          npm install
      - name: Make Gradlew Executable
        run: cd android && chmod +x ./gradlew
        # Build Command
      - name: Build Android Release and test
        run: |
          cd android && ./gradlew assembleRelease
          ./gradlew test
      # Upload to Artifact
      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: app-release.apk
          path: android/app/build/outputs/apk/release/
          
  deploy:
    needs: build-android-and-test
    runs-on: ubuntu-latest
    steps:
      - name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@v3
        with:
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.PASSPHRASE }}
          git-user-signingkey: true
          git-commit-gpgsign: true
          
      - name: Deploy to GitHub Pages
        if: success()
        uses: crazy-max/ghaction-github-pages@v2
        with:
          target_branch: gh-pages
          build_dir: android/app/build/outputs/apk/release/
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
