name: "React Native Android Build"
on:
  push:
    branches:
      - master
jobs:
  install-and-build-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install npm dependencies and build
        run: |
          npm install
          npm run build
          
  build-android-and-test:
    needs: install-and-build-npm
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install npm dependencies
        run: |
          npm install
      - name: Make Gradlew Executable
        run: cd android && chmod +x ./gradlew
        # Build Command
      - name: Build Android Release and test
        run: |
          cd android && ./gradlew assembleRelease
          ./gradlew test
      # Upload to Artifact
      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: app-release.apk
          path: android/app/build/outputs/apk/release/
